version: '3.8'

services:
  api-cotacao:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=cotacao
      - POSTGRESQL_PASSWORD=cotacao
      - POSTGRESQL_DATABASE=apicotacao